# Generated by Django 4.2.3 on 2023-07-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='install',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='location',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='location',
            name='organisation',
        ),
    ]
