# Generated by Django 4.2.3 on 2023-07-21 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('actions', models.JSONField(default=list)),
                ('constraints', models.JSONField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(related_name='objectpermissions', to='auth.group')),
                ('object_types', models.ManyToManyField(related_name='objectpermissions', to='contenttypes.contenttype')),
                ('users', models.ManyToManyField(related_name='objectpermissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
