# Generated by Django 4.2.3 on 2023-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectpermission',
            options={'ordering': ['name'], 'verbose_name': 'permission'},
        ),
        migrations.AlterField(
            model_name='objectpermission',
            name='actions',
            field=models.JSONField(default=list, help_text='The list of actions granted by this permission.'),
        ),
        migrations.AlterField(
            model_name='objectpermission',
            name='constraints',
            field=models.JSONField(blank=True, help_text='Queryset filter matching the applicable objects of the selected type(s).)', null=True),
        ),
    ]
