# Generated by Django 4.2.3 on 2023-07-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_organisation_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='group',
        ),
    ]
